// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesteEmissaoData.Data;

namespace TesteEmissaoData.Migrations
{
    [DbContext(typeof(StoreContextData))]
    [Migration("20200219143539_alter-name-column-id")]
    partial class alternamecolumnid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TesteEmissaoData.Entities.DocumentoXml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnName("cidade")
                        .HasColumnType("character(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CodCidade")
                        .IsRequired()
                        .HasColumnName("codcidade")
                        .HasColumnType("character(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnName("xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("documentoxml");
                });
#pragma warning restore 612, 618
        }
    }
}
